### ISSUE TITLE
Support for Temporal Graph

### ISSUE THREAD

**Issue by QAQOAO** [yule-BUAA/HGConv#1]
Hi, nice work in GNN! I just found this paper on the OGB leaderboard.

I wonder how could HGConv handle temporal information. In HGT, it uses RTE to encode temporal information.

I notice that the paper says HGT can be treated as a special case of HGConv, so I want to know whether it can already deal with 
 temporal information.

If not, please tell me how to achieve that, is it just adding the RTE class of HGT into the HGConv model or is there a better way of doing that?

Thanks a lot!

**Comment by yule-BUAA** [comment]
Hi,

   Thanks for your interest in our work.

   In our paper, we propose a general framework to summarize the learning paradigm of existing heterogeneous graph methods. The additional consideration of temporal information in HGT is a detailed operation in the neighbor information aggregate process, which can be involved in the aggregate process. Hence, we conclude that HGT can be treated as a special case of HGConv from a general perspective.

   In HGT, the temporal information is considered via the relative temporal encoding technique. 
    
   Currently, in the implementation of HGConv, the temporal information is still not utilized, but you could add the temporal encoding into HGConv just like what HGT does. 
    
   An intuitive way you could achieve that is to feed the relative temporal information in HGConv, and then encode the temporal information into a vector and combine the vector with the source node feature in the micro-level convolution process [above this line](https://github.com/yule-BUAA/HGConv/blob/34848efebef86d3c799eff2fc0f540dafa44710c/model/MicroConvolution.py#L59).

   Maybe a better way to consider the temporal information is to capture its semantic meanings (e.g., year, month, or week of the time) and design a dedicated encoding module to describe the temporal information.

Best wishes,

Le Yu
