### ISSUE TITLE
graph sampling on ogb-mag

### ISSUE THREAD

**Issue by shirinmous** [yule-BUAA/HGConv#2]
Hi thank you for sharing your work.
I want to know whether you use graph sampling to apply your model on ogb-mag?

**Comment by yule-BUAA** [comment]
Hi, 
    Thanks for your interest in our work.
    When training on the large-scale ogb-mag dataset, it is intractable to train our method on the whole graph directly due to the memory usage. Hence, we adopt a sampling strategy to train on ogb-mag.
    You could find the detailed implementation of neighbor sampling [from here](https://github.com/yule-BUAA/HGConv/blob/34848efebef86d3c799eff2fc0f540dafa44710c/utils/utils.py#L77) and the mini-batch training process [from here](https://github.com/yule-BUAA/HGConv/blob/34848efebef86d3c799eff2fc0f540dafa44710c/train/train_ogbn_mag.py#L142).
